import { Inter } from 'next/font/google'
import ServerStylesheet from './registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js 13 with Stitches',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ServerStylesheet>
          {children}
        </ServerStylesheet>
      </body>
    </html>
  )
}
